---
title: "CRISPR_APP_README"
author: "cbenoit"
date: "August 20, 2019"
output: md_document
# output:
#   html_document:
#     number_sections: true
#     theme: flatly
#     code_folding: hide
#     toc: yes
#     toc_float: yes
---



#Intro

Inspiré des scripts de Pierre. L'application prend en compte 4 fichiers en entrée. Elle applique une normalisation log(cpm) sur les données puis crée diverses *Distributions* pour décrire celle-ci. (Onglet Descriptive analysis) Peut être est-il possible d'incorporer par la suite la partie  écrite par Pierre dans un onfle Statistical analysis... ?  

#Input specifications

- Liste des gènes essentiels contenues dans une colonne au format texte, sans header. 
- Liste des gènes non-essentiels contenues dans une colonne au format texte, sans header. 
- Table de comptage au format csv. Les rownames correspondent aux noms de guides, les colnames aux échantillons. 
- Fichier de description des échantillons contentant une seule colonne au format texte. Respectant le format suivant. SAMPLENAME|Réplica-celltype-timepoint...


#Contact

- pierre.gestraud@curie.fr
- clement.benoit@curie.fr